# Generated by Django 5.1.4 on 2026-06-26 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RawResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, help_text='Source-provided id (parquet raw_response_id), if any.', max_length=128, null=True, unique=True)),
                ('source_url', models.URLField(blank=True, default='', max_length=512)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('parsed', 'Parsed'), ('failed', 'Failed')], default='parsed', max_length=16)),
                ('parse_error', models.TextField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='ix_raw_status'), models.Index(fields=['created_at'], name='ix_raw_created_at')],
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(max_length=64)),
                ('rate_value', models.DecimalField(decimal_places=4, max_digits=7)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('effective_date', models.DateField()),
                ('ingestion_ts', models.DateTimeField()),
                ('source_url', models.URLField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='rates.provider')),
                ('raw_response', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='rates.rawresponse')),
            ],
            options={
                'ordering': ['-effective_date', '-ingestion_ts'],
                'indexes': [models.Index(fields=['provider', 'rate_type', '-effective_date', '-ingestion_ts'], name='ix_rate_provider_type_eff'), models.Index(fields=['provider', '-effective_date', '-ingestion_ts'], name='ix_rate_provider_eff'), models.Index(fields=['rate_type', 'effective_date'], name='ix_rate_type_eff'), models.Index(fields=['ingestion_ts'], name='ix_rate_ingestion_ts')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'rate_type', 'effective_date'), name='uq_rate_natural_key')],
            },
        ),
    ]
